import Config

secret_key_base = "4FLx/oKJN3hLX9TSropfXlKX9T4Y3YwGxXvuT03LiKeTw9BAGZWODQhWK+qLK+f7"

config :ash, :policies, show_policy_breakdowns?: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :twitter, Twitter.Repo, log: false

# Configure your database
config :twitter, Twitter.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "twitter_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # ## SSL Support
  #
  # In order to use HTTPS in development, a self-signed
  pool_size: 10

# For development, we disable any cache and enable
# certificate can be generated by running the following
# debugging and code reloading.
# Mix task:
#
#
# The watchers configuration can be used to run external
#     mix phx.gen.cert
# watchers to your application. For example, we can use it
#
# to bundle .js and .css sources.
# Run `mix help phx.gen.cert` for more information.
#
config :twitter, TwitterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # The `http:` config above can be replaced with:

  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  #
  #     https: [
  #       port: 4001,
  #       cipher_suite: :strong,
  #       keyfile: "priv/cert/selfsigned_key.pem",
  #       certfile: "priv/cert/selfsigned.pem"
  #     ],
  #
  # If desired, both `http:` and `https:` keys can be
  # configured to run both http and https servers on
  # different ports.

  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: secret_key_base,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:twitter, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:twitter, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :twitter, TwitterWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/twitter_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/twitter/.*(ex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :twitter, dev_routes: true
config :twitter, token_signing_secret: secret_key_base
