defmodule Twitter.Repo.Migrations.AddReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:likes, "likes_tweet_id_fkey")

    alter table(:likes) do
      modify :tweet_id,
             references(:tweets,
               column: :id,
               name: "likes_tweet_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE likes alter CONSTRAINT likes_tweet_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:likes, "likes_tweet_id_fkey")

    alter table(:likes) do
      modify :tweet_id,
             references(:tweets,
               column: :id,
               name: "likes_tweet_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
