defmodule Twitter.Repo.Migrations.AddTweetLikes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:likes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false

      add :tweet_id,
          references(:tweets,
            column: :id,
            name: "likes_tweet_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "likes_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:likes, "likes_tweet_id_fkey")

    drop constraint(:likes, "likes_user_id_fkey")

    drop table(:likes)
  end
end
