defmodule Twitter.Repo.Migrations.AddUniqueUserTweetToLikes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:likes, [:user_id, :tweet_id], name: "likes_unique_user_tweet_index")
  end

  def down do
    drop_if_exists unique_index(:likes, [:user_id, :tweet_id],
                     name: "likes_unique_user_tweet_index"
                   )
  end
end
