defmodule Twitter.Repo.Migrations.Lab6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :disabled, :boolean, default: false
      add :admin, :boolean, default: false
    end

    alter table(:tweets) do
      add :private, :boolean, default: false
    end
  end

  def down do
    alter table(:tweets) do
      remove :private
    end

    alter table(:users) do
      remove :admin
      remove :disabled
    end
  end
end
