defmodule Twitter.Repo.Migrations.AddLabelsUserToTweets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tweets) do
      add :label, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "tweets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:tweets, "tweets_user_id_fkey")

    alter table(:tweets) do
      remove :user_id
      remove :label
    end
  end
end
